### ISSUE TITLE
Make a better README.md

### ISSUE THREAD

**Issue by AmielCyber** [AmielCyber/git-practice#2]
My readme could be better, but I'd love some suggestions to make it more clear about what this repo is!

**Comment by anekar** [comment]
I can work on this. 
Could you tell me what you want to put on README?

**Comment by AmielCyber** [comment]
> I can work on this.
> Could you tell me what you want to put on README?

Hi Anekar. 
This repo is just for me to practice using the git command line and github. 
Sorry for the confusion. 
I will try to be clear next time.
